### PR TITLE
[#115] Implement Binary File Attachments

### PR DESCRIPTION
**Pull request by Luzifer**
image
image
image
image

### CODE REVIEW

**Comment by Luzifer** [comment]
image
image

**Comment by mshedsilegx** [comment]
Perfect ! I assume that open those attachments would also invalidate (purge) them from redis, and that they would expire with the same logic as the text secret, correct ?

**Comment by mshedsilegx** [comment]
Can those attachments be added via command line driven API calls (bash script for example) as well - if yes, can an example be provided ?

**Comment by Luzifer** [comment]
> Perfect ! I assume that opening those attachments would also invalidate (purge) them from redis, and that they would expire with the same logic than the text secret, correct ?

They are in the same blob of data as the secret itself so when fetching the secret they are fetched along and instantly invalidated. So from clicking the "Show me the secret" button they cease to exist on the server and only exist in browser memory. You can download them multiple times as long as you don't close the tab. As soon as you close the tab they cease to exist.

> Can those attachments be added via command line driven API calls (bash script for example) as well - if yes, can an example be provided ?

There is not yet an example but after this has been merged before `v1.9.0` will be released I'm planning to add a CLI tool written in Go which supports attachments and secrets sharing / retrieval.

Together with that I'm gonna add a client library and markdown schema documentation how to implement the meta format.

**Comment by mshedsilegx** [comment]
Excellent.

**Comment by mshedsilegx** [comment]
image

**Pull request merged**
