### PR TITLE
Use modern and well supported crypto, improve randomness

### PR DESCRIPTION
**Pull request by evict**
This PR aims to modernise and improve the quality of the encryption used in the frontend Vue app.

Instead of using `Math.random` for generating keys ([which is not advised](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random)), I switched to a more suitable alternative. Also added code to use `AES-GCM` encryption which adds authentication and uses the browser native cryptography API, instead of using gibberish and CBC mode.

I had troubles testing the code, can you help me out to make it mergable?

### CODE REVIEW

**Comment by Luzifer** [comment]
This breaks crypto compatibility to OpenSSL. See https://github.com/Luzifer/ots/issues/17 for the discussion about this topic.

**Comment by evict** [comment]
I see. In that case it might be better to just use then secure random only in the front end.

**Comment by Luzifer** [comment]
Makes sense: in order to remove the `Math.random` generator for the password and therefore make it a little safer the password could be generated this way:

```javascript
const passwordCharset = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
const passwordLength = 20
this.securePassword = [...window.crypto.getRandomValues(new Uint8Array(passwordLength))]
    .map(n => passwordCharset[n%passwordCharset.length])
    .join('')
```

Do you want to change your PR to only change the password creation or shall I change that?

**Comment by evict** [comment]
Looks good! I am having troubles testing changes, so I think you are better equipped to make the changes and then test them properly.

**Pull request closed without merging**
